### ISSUE TITLE
Auto column size based on content in column

### ISSUE THREAD

**Issue by sachin0606** [hkalbertl/jquery.appendGrid#115]
Hi, 

can you please suggest how can i make the column size auto fit based on content within the column.

ex: [http://jsfiddle.net/MetalFrog/wexdX/](url)

**Comment by hkalbertl** [comment]
Hi,

I am afraid appendGrid cannot resize the content dynamically because textboxes exist on columns.

Unfortunately, I found this [autosize-input plugin](https://www.npmjs.com/package/autosize-input) that may help. By using this plugin, textbox can be resized based on its contents. You may use this plugin with [Custom Type](https://appendgrid.apphb.com/Demo/CustomType) on the columns that you wanted autosize.

Hope it can help :)

**Comment by sachin0606** [comment]
Thanks hkalbertl!
