### ISSUE TITLE
JSON in ui-autocomplete

### ISSUE THREAD

**Issue by tecomunico** [hkalbertl/jquery.appendGrid#117]
Good afternoon.
Can you say me how use JSON results on ui-autocomplete input ? 
Cordially,
Edgar

**Comment by hkalbertl** [comment]
Hi Edgar,

I guess you are talking about using [remote data](http://jqueryui.com/autocomplete/#remote) for ui-autocomplete. `appendGrid` will generate jQuery UI widget with options defined in `uiOption` properties. So, you can try the following code:

```javascript
$('tblAppendGrid').appendGrid({
  columns: [
    {
      name: 'AutoCompleteColumn',
      type: 'ui-autocomplete',
      uiOption: {
        // Define the custom options for initalize jQuery UI Autocomplete here
        source: '<URL to your remote data-source>'
      }
    }
  ]
});
```

Please take a look on [jQuery UI Autocomplete](http://api.jqueryui.com/autocomplete/) for the complete list of available options. Hope it can help :)

**Comment by tecomunico** [comment]
Thanks Albert, work but when i press any key always show all choices. My code is:
{ name: 'Job_', type: 'ui-autocomplete', display: 'Services',  uiOption: {source:'json/json_services.php',minLength : 2}}
My Json request show this {"Service 1", "Service 2", "Service 3"}. When I keypress any letter show Menu choice: Service 1
                        Service 2
                         Service 3

some suggestion ?
Cordially, Edgar

**Comment by hkalbertl** [comment]
Hi Edgar,

Probably it is a jQuery UI Autocomplete question.
I can see you are using PHP as backend so I tried Google and found [this thread](https://forum.jquery.com/topic/problem-using-jquery-ui-autocomplete-remote-datasource). May be you can get some idea from it.

And I would suggest you to test the options of your jQuery UI Autocomplete out of appendGrid first. Make sure the options did what you expected and then put them back to appendGrid again. For example:

```javascript
$(function(){
  /*
  $('#tblAppendGrid').appendGrid({
    // Comment your grid first
  });
  */
  $('#test').autocomplete({
    // Add and modify your options and make sure they are working well
    source:'json/json_services.php',
    minLength : 2
  });
});
```
```html
<input type="text" id="test"/>
<!--
<table id="tblAppendGrid"></table>
-->
```


Let me know if you still have difficulties on using appendGrid with jQuery UI Autocomplete :)

**Comment by richb201** [comment]
Hey Albert! How's it going? It has been quite a while since I last emailed
with you. I am having an issue with setting initial parameters
for ctrlOptions: while initializing a grid. My popup (in an Extension) has
two grids on it: GridA and GridB. I load GridA and it works fine. I then
want to load GridB but with some user choices in a drop down list. But
these choices need to be loaded into GridB's ctrlOptions before it is
initialized. So I thought maybe I could use GridA (isReady) and load up the
ctrloptions  for GridB and then initialize GridB. But I think there is
race issue. I can't seem to load up GridB's ctrloptions before GridB is
initialized. So the drop down always gets the default values.

GridA's loading is triggered when the HTML file fires this line:

<table id="tblAppendGridA">
</table>
<table id="tblAppendGridB">
</table>

Any ideas how I can set up the ctrloptions for GridB before GridA even
get's initilized (so there is no race condition)?


Thanks,

Rich Bernstein

**Comment by hkalbertl** [comment]
Hi Rich,

How about to use a function for building `ctrlOptions` in GridB?
For example:

```javascript
$(function(){
  // Init GridA
  $('#tblAppendGridA').appendGrid(...);
  // Do something or prepare ctrlOptions
  ...
  // Init GridB
  $('#tblAppendGridB').appendGrid({
    columns: [
      { name: 'DropDown', ctrlOptions: buildGridBOptions }
    ]
  });
});
function buildGridBOptions(elem){
  if (sometingIsTrue) {
    elem.appendChild(new Option('A', 1));
    elem.appendChild(new Option('B', 2));
    elem.appendChild(new Option('C', 3));
  } else {
    elem.appendChild(new Option('X', 24));
    elem.appendChild(new Option('Y', 15));
  }
}
```

In the above example, you can add logic to control which set of options to show to user for select.
May be you can try it first :)

**Comment by richb201** [comment]
Never mind Albert. I got it going. What I am now doing is requiring a user
to press a button to populate the grid. What I am really doing is building
another copy of the grid and hiding the first and then displaying the 2nd.
This was the same thing I did a while back, but I just forgot how you
helped me solve it back then. Bottom line, everything is AOK for right now.

Thanks again for a fantastic tool, Rich
