### ISSUE TITLE
Need Paging

### ISSUE THREAD

**Issue by vikasroimantra** [hkalbertl/jquery.appendGrid#123]
Is there any way to implement paging with appendgrid.

**Comment by hkalbertl** [comment]
Hi vikasroimantra,

In order to form values to submit to backend by using normal HTTP POST method , `appendGrid`  needs to generate all input elements on screen. I am afraid it is not possible to apply "paging".

You may take a look on [fix header demo](https://appendgrid.apphb.com/Demo/FixHeader) if you don't want a long table on screen. Thanks!
