### ISSUE TITLE
PHP - Load data from database

### ISSUE THREAD

**Issue by mnfsbmz** [hkalbertl/jquery.appendGrid#138]
![Capture](https://user-images.githubusercontent.com/46035185/104180842-c38b5900-5448-11eb-8378-614d3e7f063e.PNG)
![Capture2](https://user-images.githubusercontent.com/46035185/104180848-c6864980-5448-11eb-80e1-6193fd7d57e9.PNG)
![Capture3](https://user-images.githubusercontent.com/46035185/104180854-c8e8a380-5448-11eb-9b75-b88fd369fda4.PNG)
![Capture4](https://user-images.githubusercontent.com/46035185/104180858-cab26700-5448-11eb-8cb8-c04164de233c.PNG)

Help please. How can load data using myAppendGrid.load(<aray>);

**Comment by hkalbertl** [comment]
Hi mnfsbmz,

I assumed that your PHP code able get data and return them in JSON format.
In your `success` ajax callback, make sure that:
1. `myAppendGrid` is initialized
2. `result` is an array of object, see the example of [load](https://appendgrid.apphb.com/Documentation#link-load) method

If you still have problems, you may try to use ajax `done` style instead of `success`.
```javascript
$.ajax({
  url: ...
}).done(function(result){
  myAppendGrid.load(result);
});
```
