### ISSUE TITLE
Paging Functionality Request

### ISSUE THREAD

**Issue by flexifysoft** [hkalbertl/jquery.appendGrid#141]
Could you please add paging functionality it will become a awesome JavaScript control.

**Comment by hkalbertl** [comment]
Hi flexifysoft,

In order to form values to submit to backend by using normal HTTP POST method , `appendGrid`  needs to generate all input elements on screen. I am afraid it is not possible to apply "paging". Also, it is difficult to let user know if an element value is not valid on another page.

You may take a look on [fix header demo](https://appendgrid.apphb.com/Demo/FixHeader) if you don't want a long table on screen. Thanks!
