### ISSUE TITLE
getting values in onChange event in SubGrid

### ISSUE THREAD

**Issue by yadusc1588** [hkalbertl/jquery.appendGrid#80]
I am using SubGrid in my project and I came to a scenario where I want that as soon as I enter a amount in the the SPOT column, the FCT PER DAY column must be updated as FCT PER DAY = SPOTX10. I have attempted this code but it is not giving me desired results.
Please spot me what is wrong in the code.

**Here is my code**
![code](https://cloud.githubusercontent.com/assets/15044951/13660786/3166eca4-e6b3-11e5-8c56-f90ae390ea86.jpg)

**In the attached picture I have higlighted the area where on manipulation I want the calculated amount.**
![mediaplan](https://cloud.githubusercontent.com/assets/15044951/13660675/34b9d1ec-e6b2-11e5-821b-f9d967e91544.jpg)

**Comment by hkalbertl** [comment]
Hi,

I would like to ask is that you want to do "some calculation" even the user have not completed input? For example, a user wanted to enter "12345" in "Spots" and the system "should" do calculation even when the user entered "1" and calculate again when "12" are entered?

If the answer is yes, you better to consider "onkeydown" / "onkeypress" event instead of "onchange". Hope it can help. Thanks!

**Comment by yadusc1588** [comment]
Well that might also be good but the real problem I am facing is setting the value to the corresponding FCT PER DAY column cell. 
Can you help me with a code to do that?

**Comment by hkalbertl** [comment]
Hi,

Sorry that I misunderstood your question.
Please check my sample [here](https://jsfiddle.net/hkalbertl/d64gprLq/) that show you how to get and set column values in subgrid. Hope it can solve your problem :)

**Comment by yadusc1588** [comment]
Never mind.
A BIG Thanks to you Albert.
Now its working great.

**Comment by hkalbertl** [comment]
Good to know. Thanks for using `appendGrid`!
