### ISSUE TITLE
Reorder/Reload grid after remove row

### ISSUE THREAD

**Issue by tigrasti** [hkalbertl/jquery.appendGrid#87]
Hi,

I use row Id for insert data in DB. After I remove row, Id of the rows above are the same. Exmp/ I have count of 5 rows. My for loop for insert or update goes on that criteria. When I delete row no.3, rows no4 na no5 have Id that end with 4/5. How can I reload or reorder after removing row. I want to have new row order 1,2,3,4.

Best,
Bojan

**Comment by hkalbertl** [comment]
Hi,

The reason to have "1,2,4,5" instead of "1,2,3,4" is because `appendGrid` will not required to rename the name and id of generated input elements. The performance of current implementation is much better that the rename approach.

May be you can take a look on my [Server-side Handling](https://appendgrid.apphb.com/Demo/ServerHandling) demo. I used for loop as well.

If you want to keep the original row number of reference, you may define a `hidden` column type to store the value. So, you can process these values after the form is submitted to server.

Hope it can help!

**Comment by tigrasti** [comment]
Yes, 

I solved this problem in for loop temporary. Thanks a lot for plugin!

Best,
Bojan
